name: Java CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'corretto'
        java-version: '18'
    - name: Build with Gradle
      run: ./gradlew clean test
    - name: Print Results
      run: ls -al build/allure-results
