name: Autotest

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '18'
      - run: ./gradlew clean test
      - name: Start Selenoid
        uses: Xotabu4/selenoid-github-action@v2
      - name: Copy History
        uses: actions/checkout@v2
        if: always()
        with:
          ref: 'gh-pages'
          path: 'gh-pages'
      - name: Build Report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: 'build/allure-results'
          allure_history: 'allure-history'
          keep_reports: 20
      - name: Publish Report
        uses: peaceiris/actions-gh-pages@v4
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
